#!/bin/bash
# =============================================================================
# MU Online Web Droplet - Bootstrap Script
# This runs ONCE on first boot via cloud-init (user_data in Terraform)
# Terraform fills in the ${variables} before sending to DigitalOcean
# =============================================================================

set -euo pipefail  # Exit on error, undefined vars, pipe failures
exec > /var/log/mu-init.log 2>&1  # Log everything for debugging

echo "=========================================="
echo "MU Online Web Server Bootstrap Starting"
echo "Environment: ${environment}"
echo "Time: $(date)"
echo "=========================================="

# -----------------------------------------------------------------------------
# 1. System Update
# -----------------------------------------------------------------------------
echo "[1/6] Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq

# Install useful tools
apt-get install -y -qq \
  curl \
  wget \
  git \
  htop \
  ufw \
  fail2ban \
  unzip

# -----------------------------------------------------------------------------
# 2. Install Docker
# -----------------------------------------------------------------------------
echo "[2/6] Installing Docker..."
curl -fsSL https://get.docker.com | sh

# Start Docker and enable on boot
systemctl start docker
systemctl enable docker

# Verify Docker works
docker --version

# -----------------------------------------------------------------------------
# 3. Write Environment Variables for MU Website
# -----------------------------------------------------------------------------
echo "[3/6] Writing MU website configuration..."

# Store env vars in a file — Docker will load these
cat > /etc/mu-website.env << 'ENVEOF'
# MU Online Website Environment Variables
# Generated by Terraform on $(date)
DB_HOST=${mu_db_host}
DB_PORT=${mu_db_port}
DB_NAME=${mu_db_name}
DB_USER=${mu_db_user}
DB_PASSWORD=${mu_db_password}
NODE_ENV=${environment}
PORT=${mu_website_port}
ENVEOF

# Lock down permissions — DB password is in here!
chmod 600 /etc/mu-website.env

# -----------------------------------------------------------------------------
# 4. Install Docker Compose
# -----------------------------------------------------------------------------
echo "[4/6] Installing Docker Compose..."
curl -fsSL "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
  -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
docker-compose --version

# -----------------------------------------------------------------------------
# 5. Create Docker Compose file for MU Website
# -----------------------------------------------------------------------------
echo "[5/6] Creating Docker Compose configuration..."
mkdir -p /opt/mu-website

cat > /opt/mu-website/docker-compose.yml << 'COMPOSEEOF'
version: '3.8'

services:
  mu-website:
    # TODO: Replace with your actual Docker Hub image name
    # e.g. image: yourdockerhubuser/mu-website:latest
    image: nginx:alpine   # Placeholder — replace with your MU website image!
    container_name: mu-website
    restart: unless-stopped
    ports:
      - "${mu_website_port}:${mu_website_port}"
    env_file:
      - /etc/mu-website.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${mu_website_port}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

COMPOSEEOF

# -----------------------------------------------------------------------------
# 6. Basic Security Setup
# -----------------------------------------------------------------------------
echo "[6/6] Configuring basic security..."

# UFW firewall (Terraform firewall is the main one, this is a backup layer)
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp    # SSH
ufw allow ${mu_website_port}/tcp  # MU Website
ufw --force enable

# Fail2ban — auto-bans IPs with too many failed SSH attempts
systemctl start fail2ban
systemctl enable fail2ban

# Create a deployment script for future updates
cat > /usr/local/bin/mu-deploy << 'DEPLOYEOF'
#!/bin/bash
# Quick deploy script — run this to update MU website
echo "Pulling latest MU website image..."
cd /opt/mu-website
docker-compose pull
docker-compose up -d
docker-compose ps
echo "Deploy complete!"
DEPLOYEOF
chmod +x /usr/local/bin/mu-deploy

echo "=========================================="
echo "Bootstrap Complete!"
echo "MU Website config: /opt/mu-website/"
echo "Env vars: /etc/mu-website.env"
echo "To deploy: run 'mu-deploy'"
echo "Logs: /var/log/mu-init.log"
echo "=========================================="
